language: emacs-lisp
env:
  matrix:
    - EVM_EMACS=emacs-24.4-travis
    - EVM_EMACS=emacs-24.5-travis
    - EVM_EMACS=emacs-25.1-travis
    - EVM_EMACS=emacs-git-snapshot-travis
matrix:
  allow_failures:
    - env: EMACS=emacs-git-snapshot-travis
before_install:
  - git clone https://github.com/rejeep/evm.git $HOME/.evm
  - export PATH="$HOME/.evm/bin:$PATH"
  - evm config path /tmp
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - export PATH="$HOME/.cask/bin:$PATH"
install:
  - evm install $EVM_EMACS
  - evm use $EVM_EMACS
  - cask --verbose --debug
script:
  - emacs --version
  - make test EMACS="cask exec emacs"
